server:
  port: 8484

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: # jdbc url 작성
    username: # DB 계정
    password: # DB 암호
  jpa:
    # SQL로그가 나올 때 어떤 DBMS의 문법으로 출력할 것인가?
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      #ddl을 생성할때 전략
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true  #SQL 로그를 줄바꿈해서 가독성 좋게 출력
    database: mysql # DBMS계열 설정
  servlet:
    multipart:
      max-file-size: 3MB # 1개의 파일의 최대업로드 사이즈
      max-request-size: 20MB # 1번 요청에 들어올 때 최대 업로드 사이즈
logging:
  level:
    root: info
    org.hibernate.sql: debug
    com.study.todoapi : debug

jwt:
  secret: cGC4MaUIpLcelc0JK3cYbeunoub7O1b6a6Qu/Db0h7O/r9buOHtZ99qdFADLkUBMXsKGmDxtvw3fy05osq3TrA==

upload:
  path: D:/spring-prj/upload

# s3 setting
aws:
  credentials:
    accessKey: AKIAYS2NUGZYUDPE6KCV
    secretKey: 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
  region: ap-northeast-2
  bucketName: spring-todo-api-file-bucket5068
